export const ROUTES = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  DASHBOARD: '/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_PERFILES: '/admin/perfiles',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_EMPRESAS: '/admin/empresas',
  ADMIN_SUCURSALES: '/admin/sucursales',
  ADMIN_VEHICULOS: '/admin/vehiculos',
  ADMIN_CATEGORIAS: '/admin/categorias-vehiculos',
  ADMIN_ALQUILERES: '/admin/alquileres',
  CLIENT_HOME: '/cliente',
  CLIENT_EMPRESAS: '/cliente/empresas',
  CLIENT_SUCURSALES: '/cliente/sucursales',
  CLIENT_VEHICULOS: '/cliente/vehiculos',
  CLIENT_ALQUILERES: '/cliente/alquileres',
  CLIENT_CUENTA: '/cliente/cuenta',
  CLIENT_AYUDA: '/cliente/ayuda',
} as const;
